import { test } from 'node:test';
import assert from 'node:assert/strict';
import { loadStarterScientificBundle } from '../src/scientific';
import { ContractError, validateScientificBundle } from '../src/validation';
import type { AssetManifest, ScientificCatalog, SourceManifest, Measurement } from '../src/contracts';
const fresh=()=>loadStarterScientificBundle();
function rejected(mutate:(catalog:ScientificCatalog,sources:SourceManifest,assets:AssetManifest)=>void,pattern:RegExp){
 const {catalog,sources,assets}=fresh();mutate(catalog,sources,assets);
 assert.throws(()=>validateScientificBundle(catalog,sources,assets),(error:unknown)=>error instanceof ContractError&&pattern.test(error.message));
}
const quantity=<U extends string>(value:number,unit:U):Measurement<U>=>({value,unit,uncertainty:null,uncertaintyKind:'not-reported',provenance:{sourceId:'jpl-planet-physical',locator:'Synthetic contract fixture',method:'derived',note:'Test-only'}});
const kepler=()=>({model:'keplerian' as const,centerId:'sun',frame:'ECLIPJ2000' as const,epoch:{jd:2451545,timeScale:'TDB' as const},validity:{start:{jd:2451544,timeScale:'TDB' as const},end:{jd:2451546,timeScale:'TDB' as const}},accuracy:'approximate' as const,sourceId:'jpl-planet-physical',semiMajorAxis:quantity(1e8,'km'),eccentricity:quantity(0.1,'1'),inclination:quantity(0.1,'rad'),longitudeAscendingNode:quantity(0.2,'rad'),argumentPeriapsis:quantity(0.3,'rad'),meanAnomaly:quantity(0.4,'rad')});
test('eight sourced planets, partial coverage and explicit null dynamics',()=>{const {catalog}=fresh();assert.equal(catalog.bodies.filter(b=>b.kind==='planet').length,8);assert.equal(catalog.coverage.status,'partial');assert.equal(catalog.bodies.find(b=>b.id==='earth')?.physical.meanRadius?.value,6371.0084);assert.ok(catalog.bodies.every(b=>b.orbit===null&&b.rotation===null));assert.equal(catalog.bodies[0].physical.meanRadius,null);});
test('loads are isolated from caller mutation',()=>{fresh().catalog.bodies[0].name='Changed';assert.equal(fresh().catalog.bodies[0].name,'Sun');});
test('duplicate body, external and source IDs fail',()=>{rejected(c=>c.bodies.push(structuredClone(c.bodies[0])),/Duplicate ID/);rejected(c=>{c.bodies[0].naifId='10';c.bodies[1].naifId='10';},/Duplicate external/);rejected((_,s)=>s.sources.push(structuredClone(s.sources[0])),/Duplicate ID/);});
test('dangling parents, invalid barycenters and parent cycles fail',()=>{rejected(c=>{c.bodies[1].parentId='missing';},/Unknown parent/);rejected(c=>{c.bodies[1].systemBarycenterId='earth';},/barycenter/);rejected(c=>{c.bodies[0].parentId='earth';},/reference cycle/);rejected(c=>{c.bodies[1].parentId=c.bodies[1].id;},/parent itself/);});
test('moon needs a physical primary',()=>{rejected(c=>{c.bodies.find(b=>b.id==='moon')!.parentId=null;},/Moon requires/);rejected(c=>{c.bodies.find(b=>b.id==='moon')!.parentId='sun';},/physical primary/);});
test('wrong units, nonfinite and negative values fail',()=>{rejected(c=>{(c.bodies[1].physical.meanRadius as unknown as {unit:string}).unit='m';},/constant/);rejected(c=>{c.bodies[1].physical.meanRadius!.value=NaN;},/number/);rejected(c=>{c.bodies[1].physical.meanRadius!.value=-1;},/minimum/);rejected(c=>{c.bodies[1].physical.mass!.uncertainty=-1;},/minimum/);});
test('missing fields and rendering properties are rejected',()=>{rejected(c=>{delete (c.bodies[0].physical as Partial<typeof c.bodies[0]['physical']>).gm;},/Required/);rejected(c=>{Object.assign(c.bodies[1],{displayRadius:5});},/Unknown field/);});
test('provenance and uncertainty must resolve and agree',()=>{rejected(c=>{c.bodies[1].physical.meanRadius!.provenance.sourceId='missing';},/Unknown source/);rejected(c=>{c.bodies[1].physical.meanRadius!.uncertaintyKind='not-reported';},/disagree/);rejected(c=>{c.bodies[1].physical.meanRadius!.uncertainty=null;},/disagree/);});
test('schema version, real UTC dates and completeness declaration are validated',()=>{rejected(c=>{c.schemaVersion=2 as 1;},/constant/);rejected(c=>{c.releasedAtUTC='2026-02-30T00:00:00Z';},/Invalid UTC/);rejected(c=>{c.releasedAtUTC='2026-10-02';},/format/);rejected(c=>{c.coverage.status='complete-for-source-release';},/named source release/);});
test('valid Kepler metadata accepted; invalid eccentricity, angle, validity and center rejected',()=>{const b=fresh();b.catalog.bodies[3].orbit=kepler();assert.doesNotThrow(()=>validateScientificBundle(b.catalog,b.sources,b.assets));rejected(c=>{const o=kepler();o.eccentricity.value=1;c.bodies[3].orbit=o;},/maximum/);rejected(c=>{const o=kepler();o.inclination.value=4;c.bodies[3].orbit=o;},/maximum/);rejected(c=>{const o=kepler();o.epoch.jd=2451547;c.bodies[3].orbit=o;},/outside validity/);rejected(c=>{const o=kepler();o.validity.end.jd=o.validity.start.jd;c.bodies[3].orbit=o;},/precede/);rejected(c=>{const o=kepler();o.centerId='missing';c.bodies[3].orbit=o;},/cataloged center/);rejected(c=>{const o=kepler();o.sourceId='missing';c.bodies[3].orbit=o;},/Unknown source/);});
test('orbit-center graph cycles fail independently of parent graph',()=>{rejected(c=>{c.bodies[0].orbit={...kepler(),centerId:'earth'};c.bodies[3].orbit=kepler();},/orbit reference cycle/);});
test('barycenter membership is distinct from ancestry and cannot have a surface',()=>{const b=fresh();const center=structuredClone(b.catalog.bodies[0]);center.id='earth-system';center.name='Earth system';center.kind='barycenter';center.naifId=null;center.systemBarycenterId=null;b.catalog.bodies.push(center);b.catalog.bodies[3].systemBarycenterId='earth-system';b.catalog.bodies.find(body=>body.id==='moon')!.systemBarycenterId='earth-system';assert.doesNotThrow(()=>validateScientificBundle(b.catalog,b.sources,b.assets));rejected(c=>{c.bodies[1].kind='barycenter';},/no physical/);});
test('assets require reviewed licensing and checksums',()=>{const asset={id:'earth-map',bodyId:'earth',kind:'texture' as const,uri:'https://example.org/earth.png',sha256:'a'.repeat(64),byteLength:1,sourceId:'jpl-planet-physical',appearance:'illustrative' as const,license:{status:'approved' as const,identifier:'test-only',termsUrl:'https://example.org/terms',attribution:'Synthetic test asset'}};rejected((_,__,a)=>a.assets.push(asset),/reviewed source/);rejected((_,s,a)=>{s.sources[0].usage.status='approved';a.assets.push({...asset,sha256:'bad'});},/format/);const b=fresh();b.sources.sources[0].usage.status='approved';b.assets.assets.push(asset);assert.doesNotThrow(()=>validateScientificBundle(b.catalog,b.sources,b.assets));});
test('ephemeris needs a matching source/body asset',()=>{rejected(c=>{const k=kepler();c.bodies[3].orbit={model:'ephemeris',centerId:'sun',frame:'ICRF',validity:k.validity,accuracy:'source-ephemeris',sourceId:k.sourceId,assetId:'earth-ephemeris',aberration:'NONE',distanceUnit:'km',velocityUnit:'km/s'};},/Ephemeris asset/);});
